// Generated by CoffeeScript 1.3.3
var routes;

routes = function(app, passport) {
  var ensureAuthenticated, failureRedirection;
  failureRedirection = {
    failureRedirect: '/login',
    failureFlash: true
  };
  app.get('/login', function(req, res) {
    return res.render("" + __dirname + "/views/login", {
      user: req.user,
      message: req.flash('error')
    });
  });
  app.post('/login', passport.authenticate('local', failureRedirection), function(req, res) {
    return res.redirect('/');
  });
  app.get('/logout', function(req, res) {
    req.logout();
    return res.redirect('/');
  });
  return ensureAuthenticated = function(req, res, next) {
    if (req.isAuthenticated()) {
      return next();
    }
    return res.redirect('/login');
  };
};

module.exports = routes;
