// Generated by CoffeeScript 1.3.3
var LocalStrategy, User, app, express, passport, path, server, util;

express = require('express');

path = require('path');

util = require('util');

passport = require('passport');

LocalStrategy = (require('passport-local')).Strategy;

User = require('./back_end/models/user');

passport.serializeUser(function(user, done) {
  return done(null, user.id);
});

passport.deserializeUser(function(id, done) {
  return User.findById(id, function(err, user) {
    return done(err, user);
  });
});

passport.use(new LocalStrategy({
  usernameField: 'email'
}, function(username, password, done) {
  console.log('made it here!!');
  return 'I am BROKEN';
}));

app = module.exports = express();

(require('./back_end/configure'))(app, passport);

(require('./back_end/routes/index'))(app);

(require('./back_end/routes/authentication'))(app, passport);

server = app.listen(app.settings.port);

console.log("Express server listening on port " + app.settings.port + " in " + app.settings.env + " mode");
